name: Trym's Website
description: Diverse prosjekter og innhold fra studiet Fysikk og Matematikk, Sivilingeniør.
title: Tryms Nettside
markdown: kramdown
highlighter: rogue
url: "http://www.trymsaether.github.io"
